# Docker compose for TODO List database
# ------------------------------------------------------------------

# EXECUTE THIS CONTAINER INSIDE ANOTHER CONTAINER
# docker run -it --rm --network=mysql_network mysql:latest todo_list_db

version: "3.9"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: todo_list_db
    ports:
      - target: 3306
        published: 3306
    environment:
      MYSQL_ROOT_PASSWORD: todo_list
    networks:
      - mysql_network

networks:
  mysql_network:
